import 'package:Billy/models/category_model.dart';
import 'package:Billy/models/merchant_model.dart';
import 'package:Billy/models/profile_model.dart';
import 'package:json_annotation/json_annotation.dart';

@JsonSerializable()
class GroupExpenseModel {
  @JsonKey(required: true, disallowNullValue: true)

  final String id;
  final String groupId;
  final ProfileModel profileModel;
  final MerchantModel? merchant;
  final CategoryModel? category;

  final double? paidAmount;
  final double totalAmount;
  final String? splitRate; // JSON string representing how the expense is split among participants
  final String? note;
  final DateTime createdAt;
  final DateTime updatedAt;

  GroupExpenseModel({
    required this.id,
    required this.groupId,
    required this.profileModel,
    this.merchant,
    this.category,
    this.paidAmount,
    required this.totalAmount,
    this.splitRate,
    this.note,
    required this.createdAt,
    required this.updatedAt,
  });

  // TODO: Not working
  // // Note: Generated by command: flutter pub run build_runner build
  // factory GroupExpenseModel.fromJson(Map<String, dynamic> json) => _$GroupExpenseModelFromJson(json);
  // Map<String, dynamic> toJson() => _$GroupExpenseModelToJson(this);

  factory GroupExpenseModel.fromMap(Map<String, dynamic> map) {    
    return GroupExpenseModel(
      id: map['id'],
      groupId: map['group_id'],
      profileModel: ProfileModel.fromMap(map['profile']),
      merchant: map['merchant'] != null ? MerchantModel.fromMap(map['merchant']) : null,
      category: map['category'] != null ? CategoryModel.fromMap(map['category']) : null,
      paidAmount: map['paid_amount'] != null ? (map['paid_amount'] as num).toDouble() : null,
      totalAmount: (map['total_amount'] as num).toDouble(),
      splitRate: map['split_rate'],
      note: map['note'],
      createdAt: DateTime.parse(map['created_at']),
      updatedAt: DateTime.parse(map['updated_at']),
    );
  }

  static List<GroupExpenseModel> fromList(List<Map<String, dynamic>> expensesMap) {
    List<GroupExpenseModel> expenses = [];
    for (var item in expensesMap) {
      expenses.add(GroupExpenseModel.fromMap(item));
    }
    return expenses;
  }
}